resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/application-service/config/default?ref=86571e38f52e6bbe67b945dd58b695af26ae834d
  - .tekton/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: registry.build04.ci.openshift.org/ci-op-l1twwn0h/pipeline
    newTag: redhat-appstudio-has-image
configMapGenerator:
  - literals:
      - GITHUB_ORG=redhat-appstudio-qe
    name: github-config
    behavior: replace
namespace: application-service
patches:
  - ./manager_resources_patch.yaml
