resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/yangcao77/application-service/config/default?ref=961ea03b030854ecbb1161a5951a37dae334fd6f
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: registry.build02.ci.openshift.org/ci-op-7wzjbilf/pipeline
    newTag: redhat-appstudio-has-image
configMapGenerator:
  - literals:
      - GITHUB_ORG=redhat-appstudio-qe
    name: github-config
    behavior: replace
namespace: application-service
patches:
  - ./manager_resources_patch.yaml
  - ./pprof_patch.yaml
