resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/application-service/config/default?ref=275b1130701b88454284db54003c36d059f457d7

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/redhat-appstudio/application-service
  newTag: 275b1130701b88454284db54003c36d059f457d7

configMapGenerator:
- literals:
  - GITHUB_ORG=""
  name: github-config
  behavior: replace

namespace: application-service

patches:
  - ./manager_resources_patch.yaml
  - ./pprof_patch.yaml
