resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/yangcao77/application-service/config/default?ref=213dbcf15b352e7f80beeb5653b19c337b91816d
  - .tekton/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: registry.build01.ci.openshift.org/ci-op-lmh44swq/pipeline
    newTag: redhat-appstudio-has-image
configMapGenerator:
  - literals:
      - GITHUB_ORG=redhat-appstudio-qe
    name: github-config
    behavior: replace
namespace: application-service
patches:
  - ./manager_resources_patch.yaml
