resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/tkdchen/application-service/config/default?ref=6848ee67ac58f09158811198faa91b315ca97f1a
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: registry.build03.ci.openshift.org/ci-op-vpcgr8gc/pipeline
    newTag: redhat-appstudio-has-image
configMapGenerator:
  - literals:
      - GITHUB_ORG=redhat-appstudio-qe
    name: github-config
    behavior: replace
namespace: application-service
patches:
  - ./manager_resources_patch.yaml
  - ./pprof_patch.yaml
