resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/yangcao77/application-service/config/default?ref=61616c2ad5a2bdf5e2271d780673ed4804927bb8
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: registry.build05.ci.openshift.org/ci-op-lyjxjxqn/pipeline
    newTag: redhat-appstudio-has-image
configMapGenerator:
  - literals:
      - GITHUB_ORG=redhat-appstudio-qe
    name: github-config
    behavior: replace
namespace: application-service
patches:
  - ./manager_resources_patch.yaml
  - ./pprof_patch.yaml
