apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/openshift?ref=45fa68db56318d2e729010f561680008fe2f64b9

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: 45fa68db56318d2e729010f561680008fe2f64b9
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: 45fa68db56318d2e729010f561680008fe2f64b9

namespace: spi-system


patches:
  - target:
      kind: Deployment
      name: spi-controller-manager
    path: operator-limits-patch.json
patchesStrategicMerge:
  - delete-shared-configuration-file.yaml
