apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Skip applying the Tekton/PaC operands while the Tekton/PaC operator is being installed.
# See more information about this option, here: 
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types 
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - git::https://github.com/openshift-pipelines/pipeline-service.git/operator/gitops/argocd/pipeline-service?ref=a12ec9d3fe2823bb008303c52767b2cf203255ea
  - tekton-chains-controller-shared-secrets-rolebinding.yaml

patchesStrategicMerge:
  # Mount the shared secret in tekton Chains
  - tekton-chains-controller-shared-secret.yaml
  # Reset securityContext in order to be able to mount csi content
  - tekton-chains-controller-deployment.yaml
