resources:
  - allow-argocd-to-manage.yaml
  - https://github.com/tkdchen/build-service/config/default?ref=8f8af5b956e2599ef9b6cc2d2c704f5af40bf468
  - build-pipeline-selector.yaml
# Skip applying the build-service operands (BuildPipelineSelector) while the build-service operator is being installed.
# See more information about this option, here:
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
namespace: build-service
images:
  - name: quay.io/redhat-appstudio/build-service
    newName: registry.build02.ci.openshift.org/ci-op-tn06ilb6/pipeline
    newTag: redhat-appstudio-build-service-image
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
