resources:
  - allow-argocd-to-manage.yaml
  - https://github.com/mmorhun/build-service/config/default?ref=f68df75d6590ccf1e98fb130779a80e1d101018a
  - build-pipeline-selector.yaml
# Skip applying the build-service operands (BuildPipelineSelector) while the build-service operator is being installed.
# See more information about this option, here:
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
namespace: build-service
images:
  - name: quay.io/redhat-appstudio/build-service
    newName: registry.build04.ci.openshift.org/ci-op-6nmlx2lk/pipeline
    newTag: redhat-appstudio-build-service-image
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
